dnd-side-project/dnd-12th-9-frontend

- packages/ui/package.json
- packages/ui/src/lib/core.ts
- packages/ui/tsconfig.json
- pnpm-lock.yaml
close #9
- class-variance-authority, clsx, tailwind-merge 패키지 추가 했습니다.
- cn util 함수를 `packages/ui/src/lib` 폴더 내에 추가했어요. 아직은 `apps/web` 디렉토리에서 작업하지 않을 것 같아서 추가하지 않았습니다. 추후 `apps/web` 디렉토리 하위에도 추가해줘야 할 것 같습니다~!
> [CHORE] tailwind 관련 클래스 병합 유틸리티 추가

- apps/storybook/stories/Icon.stories.tsx
- apps/storybook/stories/TextField.stories.tsx
- packages/ui/src/components/Icon/Icon.tsx
- packages/ui/src/components/Icon/assets/index.ts
- packages/ui/src/components/TextField/TextField.tsx
- packages/ui/src/components/TextField/index.ts
- packages/ui/src/components/index.ts
- packages/ui/src/hooks/useTextFieldValidation.ts
close #18 
- TextField 컴포넌트, 스토리북 구현했습니다. 
- Icon 컴포넌트 `color` Props 추가했습니다~! 
- 디자이너분들께서 `maxLength`가 존재하는 예시가 디폴트라고 하셨습니다. 따라서 첨부드린 사진을 기준으로 확인해주시면 좋을 것 같습니당
> [FEAT] TextField 컴포넌트/스토리북 구현, Icon 컴포넌트 Props 추가

- apps/storybook/globals.css
- apps/storybook/stories/Icon.stories.tsx
- apps/storybook/stories/SearchBar.stories.tsx
- packages/ui/src/components/Icon/Icon.tsx
- packages/ui/src/components/Icon/assets/index.ts
- packages/ui/src/components/SearchBar/SearchBar.tsx
- packages/ui/src/components/SearchBar/index.ts
- packages/ui/src/components/index.ts
close #23 
- SearchBar 컴포넌트, 스토리북 구현했습니다. 
- Icon에 기존 `gray` -> `gray-300`변경 후 `gray-700` 색상 추가했습니다!
- 현재 `SearchBar`에서 사용 중인 추후에 `IconButton` 작업을 하려고 합니다! 디자이너 분들께서 주신 `round`가 있는 형태와 없는 형태로 제작하려 합니당
https://github.com/user-attachments/assets/35f6b736-8978-4eb9-9b5b-abee60563141
> [FEAT] SearchBar 컴포넌트, 스토리북 구현

- apps/storybook/stories/Icon.stories.tsx
- packages/ui/src/components/Icon/Icon.tsx
- packages/ui/src/components/Icon/assets/index.ts
close #33
- 이 링크에서 이야기한대로 icon Color를 수정했습니다. [관련 PR](https://github.com/dnd-side-project/dnd-12th-9-frontend/pull/32#discussion_r1951014809)
> [REFACTOR] icon color 객체 키 리팩토링

- apps/storybook/.storybook/main.ts
- apps/storybook/stories/Chip.stories.tsx
- packages/ui/src/components/Chip/Chip.tsx
- packages/ui/src/components/Chip/index.ts
- packages/ui/src/components/index.ts
close #30
- Chip 컴포넌트/스토리북 구현했습니다. 문서는 스토리북 참고해주세요!
- 해당 Chip도 포함해서 개발을 진행할까 했는데, 일반적인 Chip 보다는 closet 페이지 개발 시 component로 분리해서 개발하는 편이 낫다고 생각했습니다. 동환님 의견 궁금해요!
> [FEAT] Chip 컴포넌트,스토리북 구현

- apps/web/app/auth/callback/route.ts
- apps/web/app/login/page.tsx
> feat: 카카오 로그인

- apps/web/app/books/[id]/review/_components/ReviewContent.tsx
- apps/web/app/books/[id]/review/_constants/keyword.ts
- apps/web/app/books/[id]/review/_util/keyword.ts
- apps/web/app/books/[id]/review/page.tsx
close #67
- 평가 페이지 ui를 작성했습니다
- 키워드 선택 관련 로직을 훅으로 분리할까 했는데 api 연동하면서 분리하는 게 좋을 것 같아서 일단은 놔두었습니다.
> [FEAT] 평가 페이지 ui

- apps/web/app/_api/_accessToken.ts
- apps/web/app/_api/fetcher.ts
- apps/web/app/_constants/cookie.ts
- apps/web/app/auth/callback/route.ts
close #72
- 인증 오류시 로그인 페이지로 리다이렉트 시키는 로직을 추가했습니다
- 서버 컴포넌트에서 ky를 호출하면 server action임에도 쿠키에 접근할 수 없다고 오류가 발생하는 것 같아여... 우선은 클라이언트 컴포넌트에서 데이터 패칭을 진행해야 할 것 같습니다.
> [Feat] 인증 오류시 로그인 페이지로 리다이렉트

- apps/web/app/books/page.tsx
- apps/web/app/layout.tsx
- packages/tailwind-config/tailwind.config.ts
close #78 
- PC일때 회색 배경과 그림자를 추가했습니다
- 책장 페이지에 원래 배경색이 없었는데 하얀색을 추가했습니다
> [FEAT] PC일때 회색 배경색 추가

- apps/web/app/_api/fetcher.ts
- apps/web/app/_api/mutations/useUpdateEquippedItem.ts
- apps/web/app/_api/queries/item.ts
- apps/web/app/_api/types/item.ts
- apps/web/app/_api/types/response.ts
- apps/web/app/closet/_components/ClosetSecion.tsx
- apps/web/app/closet/_constants/item.tsx
- apps/web/app/closet/_hooks/useGhost.tsx
- apps/web/app/closet/page.tsx
close #86
- 꾸미기 페이지 api 연동했습니다
> [FEAT] 꾸미기 페이지 api 연동

- apps/web/app/layout.tsx
- apps/web/package.json
- pnpm-lock.yaml
close #90 
- speed insight를 추가해 vercel 대시보드에서 사이트 성능을 볼 수 있게 했습니다
> chore: vercel speed insights 추가

- apps/web/app/profile/_components/BottomButton.tsx
- apps/web/app/profile/_components/Card.tsx
- apps/web/app/profile/_components/Profile.tsx
- apps/web/app/profile/page.tsx
close #94 
- 자랑하기 페이지 UI 작업했습니다.
> [FEAT] 자랑하기 페이지 UI

- apps/web/app/home/_components/Home.tsx
- apps/web/app/home/_components/OnBoardingCompleteModal.tsx
- apps/web/app/onboarding/page.tsx
close #66
- 튜토리얼 모달 연결 작업했습니다!
https://github.com/user-attachments/assets/d4841929-5ab6-4fcb-bde1-b1c605fe3b98
> [FEAT] 튜토리얼 모달 연결

- apps/web/app/_components/ItemModal.tsx
- apps/web/app/_components/RewardModal.tsx
- apps/web/app/books/[id]/_components/BookStatusModal.tsx
- packages/ui/src/components/Modal/Modal.tsx
close #93
- 책 등록 후 Reward 모달 연결했습니다.
> [FEAT] 책 등록 후 Reward 모달 연결

- apps/web/app/_api/types/book.ts
- apps/web/app/books/[id]/_components/BookInfo.tsx
- apps/web/app/books/_components/CardList.tsx
- apps/web/app/search/_components/BookCard.tsx
- apps/web/app/search/_components/BookList.tsx
- apps/web/app/search/_fixture/search.ts
close #98 
- 책 등록 api 요청 dto에 thumbnailUrl 추가했습니다 ~
> [FEAT] 책 등록 api 요청 dto에 thumbnailUrl 추가

- apps/web/app/_api/types/book.ts
- apps/web/app/books/_components/BookList.tsx
close #102
- 이슈대로 api 응답값 수정해서 반영했습니다
> [FEAT] 책장 전체 조회 api 응답에 totalBookCount 추가

- apps/web/app/profile/_components/BottomButton.tsx
> fix: 공유하기 버튼 가리기

- apps/web/app/profile/_components/Profile.tsx
> fix: ios에서 이미지 다운로드 로직 수정

- apps/web/app/books/_components/BookList.tsx
- apps/web/app/closet/_components/ClosetSecion.tsx
- apps/web/app/home/_components/MemberPointInfo.tsx
close #133
- 홈 페이지 CTA 버튼 color 변경, home redirect 수정했습니다~!
> [FIX] 홈 페이지 CTA 버튼 color 변경, home redirect 수정

- apps/web/app/books/[id]/_components/DialogTrigger.tsx
- apps/web/app/books/[id]/review/_components/ReviewContent.tsx
- apps/web/app/closet/_components/ClosetSecion.tsx
- apps/web/app/layout.tsx
- apps/web/app/nickname/page.tsx
- apps/web/app/search/_components/BookList.tsx
- apps/web/app/store/_components/ItemInfo.tsx
- apps/web/package.json
- pnpm-lock.yaml
> [FEAT] 토스트 추가

- apps/web/app/books/[id]/_components/BookInfo.tsx
- apps/web/app/layout.tsx
- apps/web/app/profile/_components/Profile.tsx
> Fix: 책 정보 페이지 썸네일 안보이던 이슈 수정

- apps/web/app/layout.tsx
- apps/web/next-sitemap.config.js
- apps/web/package.json
- apps/web/public/robots.txt
- apps/web/public/sitemap-0.xml
- apps/web/public/sitemap.xml
- pnpm-lock.yaml
close #145
- 네이버 서치 어드바이저에서 본인 사이트 인증을 위한 메타 태그 추가
- next-sitemap으로 robots.txt, sitemap 추가
- 구글의 사이트 인증은 aws route53에서 진행했습니다
- 페이지 색인이 추가되면 사이트맵도 각 플랫폼에 등록하겠습니다
- next-sitemap은 나중에 걷어내고 그냥 [sitemap.ts](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap)로 설정하는 게 나을 것 같기도 합니다
> [CHORE] 검색 엔진 등록

- apps/web/app/_constants/route.ts
- apps/web/app/auth/callback/route.ts
- apps/web/app/books/[id]/_components/BackButton.tsx
- apps/web/app/books/[id]/_components/BookStatusModal.tsx
- apps/web/app/books/[id]/_components/KeywordSection.tsx
- apps/web/app/books/[id]/page.tsx
- apps/web/app/books/[id]/review/_components/ReviewContent.tsx
- apps/web/app/books/_components/BookList.tsx
- apps/web/app/books/_components/CardList.tsx
- apps/web/app/closet/_components/ClosetSecion.tsx
- apps/web/app/home/_components/Home.tsx
- apps/web/app/home/_components/HomeDrawer.tsx
- apps/web/app/home/_components/MemberPointInfo.tsx
- apps/web/app/home/_components/OnBoardingCompleteModal.tsx
- apps/web/app/home/_constants/topbar.ts
- apps/web/app/mission/_components/MissionCardList.tsx
- apps/web/app/nickname/page.tsx
- apps/web/app/page.tsx
- apps/web/app/profile/_components/Profile.tsx
- apps/web/app/store/_components/ItemInfo.tsx
close #143
- 홈에서 공유 페이지 눌렀을 때 라우팅 수정
- 클릭 이벤트 시 라우팅 경로 상수로 분리
- 리뷰 완료시
- router.replace로 책 정보페이지로 이동 (이 경우 뒤로 가기해도 책정보 페이지로 가는 문제)
- router.back으로 이동 (사용자가 url로 들어왔을 시 이슈)
우선 후자의 문제가 적게 발생한다고 판단해서 뒤로가기(책 정보 페이지)로 가도록 구현했어요. 나중에 의견 부탁드립니다~
> fix: 홈에서 공유하기 라우팅 수정

- LICENSE
close #155
- MIT 라이센스를 추가했습니다
- copyright 뒤에 저희 계정을 넣을지 sbooky를 넣을지 고민했는데 그냥 계정 넣었습니다
> [CHORE] Create LICENSE

- apps/web/app/_components/ClarityEffector.tsx
- apps/web/app/layout.tsx
- apps/web/package.json
- pnpm-lock.yaml
- turbo.json
close #150 
- Clarity 추가
- GA 추가
- GTM 추가
- Clarity는 사용자 히트맵을 보여주는 마이크로소프트의 오픈소스 모니터링 툴이에요. hotjar가 좀 더 유명했던 것 같은데 유료인 것도 있고 최근에는 Clarity가 무료고 업데이트도 계속되고 있어서 Clarity가 좀 더 핫한 것 같습니다
- GA, GAM은 추가했는데... 자세한 설정은 몰라서 조금 더 공부하거나 세빈님께 여쭤보면서 하겠습니다
- env 관리가 약간 불편한데 [@t3-oss/env-core](https://github.com/t3-oss/t3-env)를 사용해볼까 생각중입니다
> [CHORE] Clarity, GA, GTM 추가

- apps/web/app/feed.xml/route.ts
- apps/web/package.json
- pnpm-lock.yaml
close #160 
- rss 피드 추가
- 블로그처럼 모든 사용자에게 보여줄 수 있는 데이터가 있으면 효과가 더 좋았을 거 같은데.. 없는 것보다는 있는게 seo에 좋을 것 같습니다
> [CHORE] rss 피드 추가

- apps/storybook/stories/Color.mdx
- apps/storybook/stories/IconGallery.mdx
close #164 
- color, icon mdx를 추가
- 기존에 작성되어 있는 icon story가 있긴 한데 storybook에서 제공하는 icon Gallery를 활용하면 더 가시성이 좋을 것 같아서 추가했습니다.
> [FEAT] color, icon mdx 추가

- apps/web/middleware.ts
close #167
- 잘못된 미들웨어 설정으로 비로그인 유저가 무조건 닉네임 설정 페이지로 가는 이슈를 수정했습니다
- accessToken여부보다 닉네임 여부를 먼저 확인해서 발생한 문제였습니다
- accessToken 검사후에 닉네임 검사를 하도록 설정했습니다.
> [HOTFIX] middleware logic 수정
